/** Generated by scripts/generate-runtime-config.mjs. Do not edit by hand. */
export const generatedRuntimeConfig = {
  "channel": "beta",
  "environment": "integration",
  "sepBaseUrl": "https://sep-dev.longdaoSEP.cn/api",
  "gatewayUrl": "https://sep-dev.longdaoSEP.cn/api/gateway/v1",
  "buildTime": "2026-09-21T08:43:20.328Z"
} as const
