/** Generated by scripts/generate-runtime-config.mjs. Do not edit by hand. */
export const generatedRuntimeConfig = {
  "channel": "beta",
  "environment": "integration",
  "sepBaseUrl": "https://longdaosep.cn/api",
  "gatewayUrl": "https://longdaosep.cn/api/gateway/v1",
  "buildTime": "2026-09-30T01:59:52.237Z"
} as const
